### ISSUE TITLE
building on os x with Apple LLVM compiler in Xcode 5.1 fails

### ISSUE THREAD

**Issue by beOn** [PyMVPA/PyMVPA#217]
There are a few unrecognized command line options that cause building with the above mentioned version of LLVM to fail - for details see the following page:

http://kaspermunck.github.io/2014/03/fixing-clang-error/

**Comment by nno** [comment]
@beOn is this still an issue, or can it be closed?

**Comment by beOn** [comment]
Haven’t touched it for a while, but since we’re on xcode 7 at this point I’d say this specific issue can be closed.

**Comment by nno** [comment]
@beOn thanks for your reply. I agree and will close the issue.
