### ISSUE TITLE
ProcrusteanMapper(demean=False) what should happen

### ISSUE THREAD

**Issue by hanke** [PyMVPA/PyMVPA#276]
@swaroopgj I am seeing this

```
  File "..../mvpa2/mappers/procrustean.py", line 96, in _train
    data = data - mean
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```

when I train `ProcrusteanMapper(demean=False)`. Looking into ways of fixing this, I am uncertain what should happen when this argument is given.

The way the code is written, not demeaning is not an option. Should it be changed to allow for this, or should setting demean=False raise an error?

Thanks in advance.

**Comment by yarikoptic** [comment]
fixing it... imho action when demean=False should be no demeaning ;)

On Thu, 19 Feb 2015, Michael Hanke wrote:

>    @swaroopgj I am seeing this

>    File "..../mvpa2/mappers/procrustean.py", line 96, in _train
>      data = data - mean
>  TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

>    when I train ProcrusteanMapper(demean=False). Looking into ways of fixing
>    this, I am uncertain what should happen when this argument is given.

>    The way the code is written, not demeaning is not an option. Should it be
>    changed to allow for this, or should setting demean=False raise an error?

>    Thanks in advance.

>    -
>    Reply to this email directly or view it on GitHub.

>    Link: https://github.com/PyMVPA/PyMVPA/issues/276

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by swaroopgj** [comment]
Thanks!

**Comment by yarikoptic** [comment]
PR was sent out -- please review ;)
https://github.com/PyMVPA/PyMVPA/pull/277

On Thu, 19 Feb 2015, Swaroop Guntupalli wrote:

>    Thanks!

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik
