### ISSUE TITLE
hyperalignment demo hdf5 could be loaded correctly only with nibabel 1.0

### ISSUE THREAD

**Issue by yarikoptic** [PyMVPA/PyMVPA#278]
with 1.3.0:
```
$> python -c 'from mvpa2.base.hdf5 import h5load; ds= h5load("hyperalignment_tutorial_data.hdf5.gz"); print ds[0].a.imghdr ' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/pymodules/python2.7/nibabel/wrapstruct.py", line 413, in __str__
    self.endianness)
  File "/usr/lib/pymodules/python2.7/nibabel/wrapstruct.py", line 258, in endianness
    if self._structarr.dtype.isnative:
AttributeError: 'Nifti1Header' object has no attribute '_structarr'
```
originally reported: https://github.com/nipy/nibabel/issues/144#issuecomment-75419873

**Comment by hanke** [comment]
The simplest way I see forward is to recreate the dataset with code the contains gh-298

**Comment by hanke** [comment]
@nno @yarikoptic Conversion script is in and works for NiBabel jumps from 1.1 to 2.0.

From my POV this is ready to go.

**Comment by hanke** [comment]
There is now an updated dataset available at: http://data.pymvpa.org/datasets/hyperalignment_tutorial_data/hyperalignment_tutorial_data_2.4.hdf5.gz

This one doesn't need NiBabel at all to be loaded, and can work with any NiBabel (incl. v2.0) for export to NIfTI.

Closing accordingly.

**Comment by hanke** [comment]
@bcipolli Take a look, this should help your efforts.
