### ISSUE TITLE
DOI link on github points to paywall

### ISSUE THREAD

**Issue by hanke** [PyMVPA/PyMVPA#294]
@nno @yarikoptic Shall we point to the frontiers paper instead?

**Comment by yarikoptic** [comment]
we could also just point to the our draft PDF:  http://haxbylab.dartmouth.edu/publications/HHS+09a.pdf   for that one.

**Comment by hanke** [comment]
or that, but how to get DOI to resolve to that URL?

**Comment by yarikoptic** [comment]
ah -- DOI -- probably nohow :-(

**Comment by hanke** [comment]
So we could use the DOI of the frontiers paper. Objections?

**Comment by yarikoptic** [comment]
On Mon, 04 May 2015, Michael Hanke wrote:

>    So we could use the DOI of the frontiers paper. Objections?

nope
