### ISSUE TITLE
Example eventrelated.py broken

### ISSUE THREAD

**Issue by hanke** [PyMVPA/PyMVPA#311]
Mystery:

````
AttributeError: 'ConditionalAttributesCollection' object has no attribute 'confusion'
````

@hanke and @yarikoptic could reproduce it. That example is somewhat relevant for the course. Needs fixing.

**Comment by hanke** [comment]
@yarikoptic the interesting bit is: this example is not even part of the 'testexamples' makefile target -> it hasn't been tested in ages.

**Comment by yarikoptic** [comment]
Doh... fix makefile? :-) add a test to not skip any example?

**Comment by hanke** [comment]
Did the former. The latter maybe latter when time is sitting on the couch waiting for me ;-)
