### ISSUE TITLE
Uniform abbrevation of os.path.join

### ISSUE THREAD

**Issue by hanke** [PyMVPA/PyMVPA#312]
Just go through once and replace all with

````
from os.path import join as opj_
````

Vetos from @nno @yarikoptic ?

**Comment by yarikoptic** [comment]
We having similar discussion in DataLad.... May be just join? :-) unlike ly to be confused

**Comment by hanke** [comment]
My vote would be on `opj`. `join` is a string method that I'd rather not touch.

**Comment by nno** [comment]
I would prefer ``pathjoin`` because that results in more readable code. Using ``_opj`` or ``obj`` would save 4 or 5 characters, but anyone somewhat new to the code would have to look op the import statement to see what it does.

**Comment by hanke** [comment]
@nno I like that.

**Comment by nno** [comment]
Addressed in #324.
