### ISSUE TITLE
Loading niml dset fails if it doesn't contain node indices

### ISSUE THREAD

**Issue by swaroopgj** [PyMVPA/PyMVPA#332]
When trying to load surface dataset from a niml.dset file created by 3dVol2Surf without node index, niml.from_any() fails with an uninformative exception. Loading with `mvpa2.support.nibable.afni_niml_dset.read()`  shows that the problem is due to the parser not able to fine `ni_type` key in node_index tag. Digging a bit deeper shows that If the dset has no node_index info, the tag is self-closed(?) like <some_name />, but the parser still looks for ni_type.
For now, the workaround is to add node index using AFNI's ConvertDset and load the data.
@nno

**Comment by nno** [comment]
Thanks for reporting, I'll have a look.

**Comment by nno** [comment]
I confirmed the issue. A proposed fix is here: https://github.com/nno/PyMVPA/tree/_bf/niml_without_node_indices

Can you give it a try? If it works for you, I'll send out a PR.

**Comment by swaroopgj** [comment]
Works great! Thanks for quick fix Nick.

**Comment by nno** [comment]
Adressed by PR #336.
