### ISSUE TITLE
test_benchmarks_hyperalignment.py does not pass consistently

### ISSUE THREAD

**Issue by nno** [PyMVPA/PyMVPA#366]
The recent PR https://github.com/PyMVPA/PyMVPA/pull/358 authored by @yarikoptic sometimes causes a test to fail (https://travis-ci.org/PyMVPA/PyMVPA/jobs/82803155):
```
======================================================================
FAIL: mvpa2.tests.test_benchmarks_hyperalignment.test_timesegments_classification
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/PyMVPA/PyMVPA/mvpa2/tests/test_benchmarks_hyperalignment.py", line 59, in test_timesegments_classification
    assert(np.all(0.85 <= errors_nonoverlapping))
AssertionError
```
@swaroopgj suggested that the hard-coded value of 0.85 should be a function of the number of samples. In any case, the current value of 0.85 may be too high to ensure that tests pass consistently. Maybe it's better to use a lower value?

**Comment by nno** [comment]
@yarikoptic, this test is still failing. Shall we use 0.75? @swaroopgj, what do you think?

https://travis-ci.org/PyMVPA/PyMVPA/jobs/85376787

**Comment by yarikoptic** [comment]
sure... lower to 0.75 then. cheers

**Comment by nno** [comment]
I lowered to 0.75, verified that travis was happy, and pushed straight into master. All seems good now.

**Comment by yarikoptic** [comment]
On Thu, 15 Oct 2015, Nikolaas N. Oosterhof wrote:

> I lowered to 0.75, verified that travis was happy, and pushed straight into
> master. All seems good now.

cool

**Comment by yarikoptic** [comment]
was lowered and pushed to master
