### ISSUE TITLE
Do we need google analytics in PyMVPA documentation?

### ISSUE THREAD

**Issue by nno** [PyMVPA/PyMVPA#370]
The file doc/source/_themes/pymvpa_online/layout.html contains some code for google analytics:

    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));

which is considered a privacy issue by lintian (https://lintian.debian.org/maintainer/team@neuro.debian.net.html#pymvpa).

``git blame`` lists @yarikoptic as the author. Do we need this code, or can we remove it?

**Comment by yarikoptic** [comment]
thanks for digging into this one. Let's indeed strip this one away and stay on the brighter side of endeavors ;)

**Comment by yarikoptic** [comment]
was addressed by #371
