### ISSUE TITLE
coveralls coverage report includes MDP sources

### ISSUE THREAD

**Issue by hanke** [PyMVPA/PyMVPA#411]
I went through the list of files to see why we suck so much in terms of coverage. it seems that numerous files reported as having least coverage actually belong to the MDP source tree. I know too little about the setup, but maybe those could be filtered out?

**Comment by yarikoptic** [comment]
Yes they should be indeed. Strange they got in. There is some .coverage* I believe.. Can check later even not only on the phone

On January 16, 2016 9:02:16 AM EST, Michael Hanke <notifications@github.com> wrote:
>I went through the list of files to see why we suck so much in terms of
>coverage. it seems that numerous files reported as having least
>coverage actually belong to the MDP source tree. I know too little
>about the setup, but maybe those could be filtered out?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/PyMVPA/PyMVPA/issues/411

-- 
Sent from a phone which beats iPhone.
