### ISSUE TITLE
Memory consumption by SVM

### ISSUE THREAD

**Issue by bertholdl** [PyMVPA/PyMVPA#443]
Dear PyMVPA team,

I suspect a memory leak in the SVM wrappers. Consider this example:

```
import mvpa2.datasets.base
import mvpa2.clfs.svm
import numpy as np

ds = mvpa2.clfs.base.Dataset.from_wizard(samples=np.random.uniform(size=[80, 10000]), targets=np.random.uniform(size=[80]))
for _ in range(2000):
    svm = mvpa2.clfs.svm.SVM(svm_impl="EPSILON_SVR", C=1, kernel=mvpa2.kernels.libsvm.LinearLSKernel())
    svm.train(ds)
    svm.predict(ds)
```

I could run this with PyMVPA 2.4.1 on a (Neuro)Debian machine without problems. However, after upgrading the packages `python-mvpa2` and `python-mvpa2-lib` to their most recent versions via apt (`mvpa2.__version__` prints 2.4.2 after), running this code will result in ever increasing memory consumption (and is sometimes stopped by the OS as a last resort). Is this intended behavior or a memory leak?

Kind regards,
Laurens Berthold

**Comment by yarikoptic** [comment]
On Mon, 14 Mar 2016, bertholdl wrote:

>    Dear PyMVPA team,

>    I suspect a memory leak in the SVM wrappers. Consider this example:

>  import mvpa2.datasets.base
>  import mvpa2.clfs.svm
>  import numpy as np

>  ds = mvpa2.clfs.base.Dataset.from_wizard(samples=np.random.uniform(size=[80, 10000]), targets=np.random.uniform(size=[80]))
>  for _ in range(2000):
>      svm = mvpa2.clfs.svm.SVM(svm_impl="EPSILON_SVR", C=1, kernel=mvpa2.kernels.libsvm.LinearLSKernel())
>      svm.train(ds)
>      svm.predict(ds)

>    I could run this with PyMVPA 2.4.1 on a (Neuro)Debian machine without
>    problems. However, after upgrading the packages python-mvpa2 and
>    python-mvpa2-lib to their most recent versions via apt (mvpa2.__version__
>    prints 2.4.2 after), running this code will result in ever increasing
>    memory consumption (and is sometimes stopped by the OS as a last resort).
>    Is this intended behavior or a memory leak?

Smells like a memory leak! Sorry about that.  in this release I have
redone swig bindings so they stay compatible with newer swig and I guess
that is where this issue came up.  I will look into it asap -- thanks
for the report and the snippet!

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by yarikoptic** [comment]
Thanks again @bertholdl -- if above fix didn't break anything I will merge it in and will probably release a quick release (hopefully by tomorrow morning should get into neurodebian).  BTW, one feature you could have used is "metrics" for debug msgs in PyMVPA one of which reports memory consumtpion at point of the debug msg:

```
from mvpa2.base import debug
debug.metrics += ['vmem']
debug.register('XXX', '')
debug.active += ['XXX']
...
for _ in range(20000):
    debug('XXX', "Iter %d" % _)
...
```
then you could see smth like
```
[XXX] DBG{RSS/VMS: 142152/537796 kB}:Iter 0
[XXX] DBG{RSS/VMS: 272260/667716 kB}:Iter 1
[XXX] DBG{RSS/VMS: 278404/673848 kB}:Iter 2
[XXX] DBG{RSS/VMS: 278408/673848 kB}:Iter 3
[XXX] DBG{RSS/VMS: 278412/673848 kB}:Iter 4
```

**Comment by bertholdl** [comment]
That was fast as lightning! Thank you :-) Also, nice to know that bit about the metrics.
