### ISSUE TITLE
SplitRFE example code incomplete

### ISSUE THREAD

**Issue by zingbretsen** [PyMVPA/PyMVPA#460]
[SplitRFE](http://www.pymvpa.org/generated/mvpa2.featsel.rfe.SplitRFE.html)

rfesvm_split is used in the errorfx, but is not shown previously in the code.

In the regular RFE example, rfesvm_split is used in 2 places--as the first argument (with get_sensitivity_analyzer) as well as in the ConfusionBasedError.
[RFE](http://www.pymvpa.org/generated/mvpa2.featsel.rfe.RFE.html)

Should that be the same in the SplitRFE example? That is, should the first argument not be a separate instance of the SVM classifier? Or is rfesvm_split even necessary in this example?

```
>>> # Lazy import
>>> from mvpa2.suite import *
>>> # design an RFE feature selection to be used with a classifier
>>> rfe = SplitRFE(
...           LinearCSVMC(),
...           OddEvenPartitioner(),
...           # take sensitivities per each split, L2 norm, mean, abs them
...           fmeasure_postproc=ChainMapper([
...               FxMapper('features', l2_normed),
...               FxMapper('samples', np.mean),
...               FxMapper('samples', np.abs)]),
...           # use the error stored in the confusion matrix of split classifier
...           errorfx=ConfusionBasedError(rfesvm_split, confusion_state='stats'),
...           # select 50% of the best on each step
...           fselector=FractionTailSelector(
...               0.50,
...               mode='select', tail='upper'),
...           # but we do want to update sensitivities on each step
...           update_sensitivity=True)
```

**Comment by yarikoptic** [comment]
thank you for the report!  indeed, `errorfx` is optional here so I will push the "fix" which simply omits that specification here.
