### ISSUE TITLE
Error importing mvpa2.support.scipy.stats

### ISSUE THREAD

**Issue by bertholdl** [PyMVPA/PyMVPA#489]
Hello,

after upgrading my Python ecosystem via pip, I encountered an error importing mvpa2.support.scipy.stats :
```
In [1]: import mvpa2.support.scipy.stats
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-7d26136829f3> in <module>()
----> 1 import mvpa2.support.scipy.stats

/usr/lib/python2.7/dist-packages/mvpa2/support/scipy/stats.py in <module>()
     60                       )
     61     # Fix up number of arguments for veccdf's vectorize
---> 62     if rdist.veccdf.nin == 1:
     63         if __debug__:
     64             debug("EXT", "Fixing up veccdf.nin to make 2 for rdist")

AttributeError: 'rdist_gen' object has no attribute 'veccdf'
```

Unfortunately, I did not pay attention to the names of the packages being upgraded; SciPy might have been among them - it is now version 0.18.0. This also breaks other depending modules, e.g. mvpa2.measures.searchlight or mvpa2.clfs.svm.
Edit: PyMVPA version is 2.5.0

**Comment by yarikoptic** [comment]
On Wed, 10 Aug 2016, bertholdl wrote:

>    Unfortunately, I did not pay attention to the names of the packages being
>    upgraded; SciPy might have been among them - it is now version 0.18.0.
>    This also breaks other depending modules, e.g. mvpa2.measures.searchlight
>    or mvpa2.clfs.svm.

great -- thanks for the report!  I will look into it!

**Comment by cosmozhang** [comment]
It occurred again.
