### ISSUE TITLE
(Quasi)Deterministic Balancer

### ISSUE THREAD

**Issue by effigies** [PyMVPA/PyMVPA#492]
I've realized that the `Balancer` is random with each call through `generate`, which means that on a cross-validated searchlight analysis, each searchlight may have an entirely different training set. It may be (and, in my case, is) preferred for an entire searchlight analysis to be performed with the same (random) trials excluded, and do multiple searchlight analyses in order to get the resampling desired.

As I see it, the advantage to a non-deterministic `Balancer` is that a smooth region of high classification accuracy is now a "stronger" indicator of information than one in which neighboring searchlights share nearly identical feature vectors, but in a way that seems pretty hard to quantify. By pulling making `Balancer` deterministic in an object-local sense, searchlight becomes a static mapping function, which is easier to reason about. (This applies to all repeated measures.)

I believe that, due to the multiprocessing being process- rather than thread-based, this would actually be a fairly simple modification of saving the random state at `Balancer` creation, and resetting it at the beginning of `generate`, but I'd need to do some testing. It could be necessary to lock around `self(ds)` abd setting/saving state before and after.

So before going much further, I'd like to get some opinions: Would PyMVPA add an object-locally deterministic Balancer? And, if so, should that be (a) standard behavior, (b) optional (`__init__` parameter) behavior, or (c) a subclass?

**Comment by yarikoptic** [comment]
THANKS! See/review/feedback #493? ;)
