### ISSUE TITLE
Change colormap in scatter

### ISSUE THREAD

**Issue by mvdoc** [PyMVPA/PyMVPA#531]
Let's skip jet and use a nice seaborn colormap 

@yarikoptic please assign me :D

**Comment by yarikoptic** [comment]
Should be an option if not already... My visual system already tuned up for current default in posterior to anterior

**Comment by mvdoc** [comment]
Option...but wouldn't a different default be better? ;)

**Comment by yarikoptic** [comment]
May be, if shown to lead to more discriminable information being presented ;-)
