### ISSUE TITLE
GroupClusterThreshold: Cluster labels are grouped in vertical stripes

### ISSUE THREAD

**Issue by shimsei** [PyMVPA/PyMVPA#562]
I‌ have attached the resulting figure of fa.clusters_fwe_thresh from GroupClusterThreshold.
Even though the voxels have a shared face they are grouped into different clusters resulting in strange significant vertical lines of voxels over the brain.

![stripes_groupcluster](https://user-images.githubusercontent.com/32793196/34381720-8d6aefec-eb1f-11e7-9859-888fb4978470.png)

**Comment by nno** [comment]
Thanks for the report. This seems strange indeed. Could you please provide more details about the script / code that you used to generate the data that you visualised?

**Comment by shimsei** [comment]
We have 2 conditions in each run and use their corresponding beta maps in each run. 
I used 100 permutations for 15 subject with MCNullDist to estimate the null distribution. Saved 1500 accuracy maps and used GroupClusterThreshold for the bootstrapping.

The region itself makes sense as we have got more or less the same region from GLM and usual searchlight compared to a fixed chance level. 

This is the whole script:

`
	
	file_path = glob.glob('../data')[0] 
	sbjs = os.listdir(file_path)[:] 
	working_path = glob.glob('../decoding')[0]  

	first_level_directory = "design_lang_hrf_catchout" # directory name of betas
	searchlight_radius = 4

	print sbjs
	nsbj = len(sbjs)
	nbin = 2 # the number of bins to include in analysis
	nbeta = 10 # the total number of beta images per run

	nperm = 100
	nbootstrap = 10000

	mask_path ='./mask/mask.nii'
	mask = fmri_dataset(mask_path, mask = mask_path)
	n = 0
	for ibin in range(nbin):
	        group_dataset = np.zeros((mask.shape[1], nsbj*iter*nperm))
	        group_chunk = np.zeros(nsbj*iter*nperm)
	        mean_map = np.zeros((1,mask.shape[1]))
	        n = 0
	        n_null_sample = 0
	        print "bin ", ibin
	        for isbj in range(nsbj):
	                sbj_path = '%(path)s/%(sbj)s' % \
	                        {"path": file_path, "sbj": sbjs[isbj]}
	                run_path = glob.glob('%(sbj_path)s/Main_*' % \
	                        {"sbj_path": sbj_path})
	                nrun = len(run_path) - 1 # first directory is not analysed

	                beta_path = '%(sbj_path)s/%(first_level)s' % \
	                        {"sbj_path": sbj_path, "first_level": first_level_directory}

	                print 'Sbj ', sbj_path
	                if os.path.exists(beta_path): # if the first level directory exist
	                        # create result directory ../decoding/free[sbj_name]
	                        command = 'mkdir -p %(path)s/%(sbj)s' % \
	                                {"path": working_path, "sbj": sbjs[isbj]}
	                        p = subprocess.Popen(command, shell=True) 

	                        # prepare list of files to be loaded, their target and chunck value
	                        beta_list = []
	                        chunck_list = []
	                        target_list = []
	                        print sbjs[isbj], "bin", ibin+1
	                        for irun in range(nrun): 
	                                # first select english bin
	                                ibeta = nbeta*irun + ibin + 1
	                                beta_list.append('%(beta_path)s/beta_%(ibeta)04d.nii' % {"beta_path": beta_path, "ibeta": ibeta})
	                                chunck_list.append(irun+1)
	                                target_list.append(1) # value given to english

	                                # then select german bin
	                                ibeta = nbeta*irun + ibin + 3
	                                beta_list.append('%(beta_path)s/beta_%(ibeta)04d.nii' % {"beta_path": beta_path, "ibeta": ibeta})
	                                chunck_list.append(irun+1)
	                                target_list.append(-1) # value given to german
	                                print "run ", irun

	                        # load the dataset prepared above
	                        print "loading data"
	                        dataset = fmri_dataset(beta_list, mask = mask_path, targets = target_list, chunks = chunck_list)
	                        print('dataset size:', dataset.shape)
	                        # choose classifier
	                        clf = LinearCSVMC()
	                        splt = NFoldPartitioner(attr='chunks')

	                        # setups for Monte Carlo Null distribution estimation
	                        # enable progress output for MC estimation
	                        if __debug__:
	                                debug.active += ["STATMC"]
	                        permutator = AttributePermutator('targets', count=nperm, limit='chunks')
	                        distr_est = MCNullDist(permutator, tail='left', enable_ca=['dist_samples'])

	                        # setup measure to be computed by Searchlight
	                        # cross-validated mean transfer using an N-fold dataset splitter
	                        cv = CrossValidation(clf, splt, errorfx = mean_match_accuracy)

	                        # set searchlight parameters
	                        sl = sphere_searchlight(cv, radius = searchlight_radius, space='voxel_indices', null_dist=distr_est, nproc=16, postproc = mean_sample(), enable_ca=['roi_sizes', 'null_t'])
	                        # for speed up get rid of unnesessary stuff, and Nans
	                        print "clean up ..."
	                        ds = dataset.copy(deep=False, sa=['targets', 'chunks'], fa=['voxel_indices'], a=['mapper'])
	                        ds.samples = np.nan_to_num(ds.samples)

	                        # run the searchlight. 
	                        sl_map = sl(ds)
	                        group_dataset[:,n_null_sample:n_null_sample+nperm] = distr_est.ca.dist_samples
	                        group_chunk[n_null_sample:n_null_sample+nperm] = isbj
	                        n_null_sample += nperm

	                        print('sl map size ',sl_map.shape)
	                        mean_map += sl_map.samples
	                        n += 1
	                        # save searchligh map for subject
	                        print "saving results"
	                        results_path = '%(path)s/%(sbj)s/%(name)s_catchout_all_c_r%(r)d_slmap_mean_bin%(ibin)02d.nii' % \
	                                {"path": working_path, "sbj": sbjs[isbj], "r": searchlight_radius, "name": first_level_directory, "ibin": ibin+1}
	                        niftiresults = map2nifti(sl_map, imghdr=dataset.a.imghdr)
	                        niftiresults.to_filename(filename = results_path)

	                else:
	                        print "skipping sbj ", sbjs[isbj], ". First level directory does not exist."


	        perms = dataset_wizard(samples=group_dataset.T, chunks=group_chunk)

	        results_path = '../%(name)s_perms_c_r%(r)d_bin%(ibin)02d_v4.hdf5' % \
	                {"r": searchlight_radius, "name": first_level_directory, "ibin": ibin+1}
	        perms.save(results_path)
	        del ds
	        del group_dataset
	        mean_map = mean_map/float(n)
	        mean_map = dataset_wizard(samples=mean_map)
	        results_path = '../%(name)s_meanmap_c_r%(r)d_bin%(ibin)02d_v4.hdf5' % \
	                {"r": searchlight_radius, "name": first_level_directory, "ibin": ibin+1}
	        mean_map.save(results_path)
	        # Create bootstrapping of those permutation results
	        clthr = gct.GroupClusterThreshold(n_bootstrap = nbootstrap)
	        # Do all the bootstrapping
	        print('bootstrapping ...')
	        clthr.train(perms)
	        # Estimate significance/treshold your original map (mean of errors across subjects without permutations)
	        print('Estimate significance/treshold ...')
	        res = clthr(mean_map)

	        print('saving group cluster results')
	        results_path = '../%(name)s_groupthr_c_r%(r)d_fwethresh_bin%(ibin)02d_v4.nii' % \
	                {"r": searchlight_radius, "name": first_level_directory, "ibin": ibin+1}
	        niftiresults = map2nifti(mask, data=res.fa.clusters_fwe_thresh, imghdr=dataset.a.imghdr)
	        niftiresults.to_filename(filename = results_path)

	        results_path = '../%(name)s_groupthr_c_r%(r)d_dataset_bin%(ibin)02d_v4.hdf5' % \
	                {"r": searchlight_radius, "name": first_level_directory, "ibin": ibin+1}
	        res.save(results_path)                        
`

**Comment by nno** [comment]
@shimsei as you closed the issue: do you know or figure out what caused the stripes? Thanks!

**Comment by shimsei** [comment]
It was a bug in my code. I was saving the null sample in a numpy array and when changing it to a dataset using dataset_wizard the voxel indices were messed up in the mean_map and permutations (perms) dataset. It was solved by setting fa.voxel_indices of mean_map and perms equal to the original data.

**Comment by nno** [comment]
Thanks for the feedback, and good to hear there does not seem to be an issue with the PyMVPA code :-)

**Comment by JiyeongHa** [comment]
I'm also having the same problem. I tried to set fa.voxel_indices of my mean_map and perms equal like >> perm_map.fa['voxel_indices'] = mean_map.fa['voxel_indices'] but I still see the stripe patterns in the results. Could you explain in detail how you set those two voxel indices equal?

**Comment by shimsei** [comment]
In my code both mean_map and perm_map had wrong voxel_indices. I guess you should first correct the mean_map voxel_indices then assign it to perm_map.fa['voxel_indices'] .
