### ISSUE TITLE
mvpa2-lib 2.6.3 package appears to break smlr.

### ISSUE THREAD

**Issue by ddwagner** [PyMVPA/PyMVPA#564]
Hi all, is it possible neurodebian's 2.6.3 binaries for mvpa2-lib are breaking SMLR (the c version)? Upgraded from 2.6.1 on Trusty and from 2.6.0 on Xenial (in a VM) and am now getting warnings that mvpa2 is failing to load the C implementation of SMLR.  Was able to reproduce by reverting to a VM snapshot of 2.6.0 made just prior to the upgrade. Everything installed via apt with the neurodeb repositories.

**Comment by yarikoptic** [comment]
ha ha -- hot topic!  sorry I have missed your report -- was traveling and there was exposed to the issue, which was today duplicated in #568 .  A Debian package with a workaround is cooking up and should appear later today as 2.6.4-1 package.

**Comment by yarikoptic** [comment]
Fixed in 2.6.4-1 debian version of the package, uploaded all around now, should work ;-)

**Comment by ddwagner** [comment]
Looks good on trusty and xenial! thanks.
