### ISSUE TITLE
ImportError: No module named modshogun

### ISSUE THREAD

**Issue by BrianOdegaard** [PyMVPA/PyMVPA#598]
After having success with pymvpa in Neurodebian, I have begun setting up a new work station which uses virtual environments in Anaconda.

Unfortunately, after installing pymvpa in my virtual environment using conda install -c conda-forge pymvpa2, when I try to load data with previous commands that worked, I get the error shown below.

Commands:
from mvpa2.suite import *
pathhrfAll = 'path_to_my_data'
hrfAll = h5load(pathhrfAll)

Error (truncated here for readability):
  File "/anaconda3/envs/decnef_environment/lib/python2.7/site-packages/mvpa2/base/hdf5.py", line 255, in _recon_customobj_customrecon
    mod, recon = _import_from_thin_air(mod_name, recon_name)
  File "/anaconda3/envs/decnef_environment/lib/python2.7/site-packages/mvpa2/base/hdf5.py", line 316, in _import_from_thin_air
    raise e
ImportError: No module named modshogun

This error emerges using anaconda3, python2.7, Spyder 3.3.2, on Mac 10.14.3
Installing Shogun in the virtual environment did not fix the error.  
Any advice would be greatly welcomed.  Thank you.

**Comment by yarikoptic** [comment]
The hdf5 fines your saved in another environment aren't guaranteed to be movable into another one. I would just recompute whatever model you have stored in them. Having said that, you could try installing Shogun of the same version you had in the original one, verifying that you can import it using import modshogun, and then trying again to load.

**Comment by BrianOdegaard** [comment]
Thanks for the suggestion about recomputing things in my own environment; it works.

But just a heads-up for anyone else with this issue: trying to run pymvpa2 in conda with the latest version of shogun installed didn't work, but if you downgrade shogun to one of the older versions that's still supported (e.g., version 6.0), it works.  So it looks like something in the latest shogun version causes it to break.

**Comment by yarikoptic** [comment]
thanks for the follow up! I guess their API has changed -- haven't looked at the beast for a while. 
Since there is nothing for us to do more here, I will close it for now ;-)
