### ISSUE TITLE
mvpa-scatter tool/module into PyMVPA

### ISSUE THREAD

**Issue by yarikoptic** [PyMVPA/PyMVPA#61]
Move it into PyMVPA

TODO:

 - coloring based on .fa (may be .sa for 4D?)

**Comment by hanke** [comment]
@yarikoptic It's been a year ;-) Removing this from the release milestone.

**Comment by yarikoptic** [comment]
Please don't just remove -- reassign to the next one. (Tried to do on the phone, but didn't work even in desktop mode)

**Comment by hanke** [comment]
@yarikoptic doing now

**Comment by yarikoptic** [comment]
done by #494, thanks @mvdoc
