### ISSUE TITLE
ModuleNotFoundError: No module named 'mvpa2'

### ISSUE THREAD

**Issue by mndhub** [PyMVPA/PyMVPA#623]
I have installed pymvpa and it runs in Terminal, but it doesn't work in visual studio (env python 2.7). How can I solve it?

**Comment by yarikoptic** [comment]
it depends on how you installed it, and either the VS python is the same (e.g. if you used virtualenv or conda env) as the one you have in Terminal.  Make sure that VS uses the same python.  On linux there is a `which` command which would tell you.  On windows there is none such, so you could use this helper https://github.com/datalad/datalad/blob/HEAD/tools/which.py

**Comment by mndhub** [comment]
It works! Thanks
