### ISSUE TITLE
tsv output file rsa pymvpa

### ISSUE THREAD

**Issue by mariagiuliat** [PyMVPA/PyMVPA#636]
Hi everyone!
I am using the PyMVPA toolbox in the BIDS-app. I have completed the classification and RSA analysis, obtaining the dissimilarity matrix (distance: correlation) on the subject's HTML. However, I cannot find the TSV file where the correlation values of the matrix are reported. In Torabian et al., 2023 it is mentioned that the RSA output is also saved into a TSV file.
I'd need the correlation values for further analysis. Do you know where this output is saved? or why I cannot see it? 
Thank you!

**Comment by yarikoptic** [comment]
ping @sajjadtorabian , and indeed the
- https://github.com/bids-apps/PyMVPA/issues/21
is a more appropriate location IMHO, so I will close this one here as a duplicate
